import Head from 'next/head'
import Image from 'next/image'
import SERVER from '../public/constants/server'
import { useTranslations } from 'use-intl'
// import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
// import { useTranslation } from 'next-i18next';

// export async function getStaticProps({ locale }) {
//   return {
//     props: {
//       ...(await serverSideTranslations(locale, ['common'])),
//       // Will be passed to the page component as props
//     },
//   };
// }

// pages/index.js
export async function getStaticProps({ locale }) {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by language and read
      // the desired one based on the `locale` received from Next.js.
      messages: (await import(`../messages/index/${locale}.json`)).default
    }
  }
}

export default function Home() {
  // const { t } = useTranslation('common');
  const t = useTranslations('Index')
  console.log(process.env.NEXT_PUBLIC_BUILD_ENV)
  console.log(SERVER.SERVER_URL)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {t('title')}
        {/* <h1 className={styles.title}>{t('title')}</h1> */}
      </main>
    </div>
  )
}
